### ISSUE TITLE
Final release for usage ?

### ISSUE THREAD

**Issue by JCL38-ORANGE** [bosh-packages/java-release#1]
Hello,

When do you plan to bump the final release ?
Thanks and regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

Any news for the final release ?
Thanks and regards,
Jean-Christophe.

**Comment by bgandon** [comment]
@cppforlife: as JC said, we are missing a public blobstore in `config/final.yml`, and some final release too!

**Comment by bgandon** [comment]
@JCL38-ORANGE : for your information I've ping-ed @cppforlife (Dimitri) yesterday and he said he would configure his CI soon and publish the blob.

In the meantime, we can integrate this blob manually : https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_141.tar.gz

**Comment by bgandon** [comment]
Sorry Jean-Christophe @JCL38-ORANGE, I gave you the JDK link from [hybris/java-boshpackage](https://github.com/hybris/java-boshpackage) whose SHA1 does not match.

Actually, Dimitry included [the JRE](https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_141.tar.gz) in this BOSH Package, whose SHA1 is properly `fef57709d2ca0b375a3879fe03df303afe24307f` as stated in the `config/blobs.yml` file here.

So *that* is our blob!

**Comment by neil-hickey** [comment]
@cppforlife any news on creating final release?

**Comment by cppforlife** [comment]
@neil-hickey back from vacation, will try to finish this up shortly.

**Comment by bgandon** [comment]
@cppforlife Oh yes, please!

**Comment by alex-slynko** [comment]
@cppforlife are there any news on this?

**Comment by cppforlife** [comment]
almost there (on wip branch), may be even will complete tomorrow for jdk 8 and 9.

**Comment by bgandon** [comment]
Great news! Thank you Dmitriy!

**Comment by obeyler** [comment]
Hello @cppforlife  Have you some new of  release ?

**Comment by bgandon** [comment]
Hi @cppforlife, the WIP branch looks very good!
Any news about creating a final release here, shipping OpenJDK 8 and 9 ?

(Sorry Dmitriy, but It's been 6 months since we started needing this, and we can't wait anymore. If not possible that you publish a final release within the following weeks, I'll fork a `gk-java-release` in Gstack Github org and publish a final release there.)

**Comment by cppforlife** [comment]
putting it in ci finally...

**Comment by cppforlife** [comment]
and ci went through... v1 (https://github.com/bosh-packages/java-release/releases/tag/v1) is published. i've tried it out with my test kafka release and it seems to work.

**Comment by cppforlife** [comment]
checked in build.logs (eg https://github.com/bosh-packages/java-release/blob/master/packages/openjdk-9/build.log) also show build steps taken.

**Comment by bgandon** [comment]
Great! Thank you @cppforlife!
