### ISSUE TITLE
Java 17

### ISSUE THREAD

**Issue by KevinJCross** [bosh-packages/java-release#15]
Hi,
Is it possible to add the next java LTS to this project?
@mariash @dlresende ?
Is this project still under active maintenance?

**Comment by silvestre** [comment]
@mariash @klakin-pivotal We would be happy to contribute, however it seems the CI is not open to the public, so we would have to  mirror it first on our side, and we would like to get your input that this is a worthwhile investment on our side. :slightly_smiling_face: 

/cc @rkoster
