### ISSUE TITLE
Java release uses the same package name for all patches of a java major version

### ISSUE THREAD

**Issue by BeckerMax** [bosh-packages/java-release#6]
Many bosh releases have a dependency to this `java-release`. When the `java-release` updates it's `openjdk` package it leads to a failing deployment with name collision error as described in this issue https://github.com/cloudfoundry/bosh/issues/1940.
A solution is to change the package name of openjdk-8 when bumping its version as done for the ruby package here https://github.com/bosh-packages/ruby-release/tree/master/packages.

@beyhan, @beckermax

**Comment by cppforlife** [comment]
any particular releases that collide, we've only done this for ruby to avoid cpi + director collision.

**Comment by voelzmo** [comment]
I think in this case it is two internal releases. Anyways, isn't this already a problem with a single release where you update the java version of your vendored package? The old package will remain on the VM and the new one has the same name – doesn't that collide in all cases?

I guess it should be good practice to adjust the names of your vendored packages with every update if they are runtime dependencies. Stuff like golang doesn't have these problems as it is just needed during compile time.
